
PROGRAM _INIT
	(* Insert code here *)
	 
END_PROGRAM

PROGRAM _CYCLIC
	(* Insert code here *)
	
	IF Start AND NOT Done THEN
		TestAction;
	END_IF
	
	CASE MachineState OF
		
		cwINIT:
		
		cwWAITING:
		
		cwENTRANCE:
		
		cwCHEMICALS:
		
		cwHIGH_PRESSURE:
		
		cwHBRUSH:
		
		cwVBRUSH:
		
		cwUNDERBODY:
		
		cwPOLISH_HBRUSH:
		
		cwPOLISH_VBRUSH:
		
		cwHOT_WAX:
		
		cwDRYING:
		
		cwERROR:
		
		cwEXIT:
		
		  

	END_CASE;
	
	
	
	
	
	
	
	
	 
END_PROGRAM

PROGRAM _EXIT
	(* Insert code here *)
	 
END_PROGRAM

